[2022-09-06T14:56:49.702+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-09-06T14:56:49.728+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-09-06T14:56:49.728+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:49.729+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:56:49.729+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:49.765+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-04-30 00:00:00+00:00
[2022-09-06T14:56:49.775+0000] {standard_task_runner.py:52} INFO - Started process 283 to run task
[2022-09-06T14:56:49.790+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-04-30T00:00:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpzpjs36ek', '--error-file', '/tmp/tmpc5f9zzxk']
[2022-09-06T14:56:49.796+0000] {standard_task_runner.py:80} INFO - Job 431: Subtask postgres_to_s3
[2022-09-06T14:56:50.017+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:56:50.361+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-30T00:00:00+00:00
[2022-09-06T14:56:50.389+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:56:51.015+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    with open("dags/get_orders.txt" "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dags/get_orders.txtw'
[2022-09-06T14:56:51.041+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220430T000000, start_date=20220906T145649, end_date=20220906T145651
[2022-09-06T14:56:51.263+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 431 for task postgres_to_s3 ([Errno 2] No such file or directory: 'dags/get_orders.txtw'; 283)
[2022-09-06T14:56:51.312+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T14:56:51.547+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T14:59:47.624+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-09-06T14:59:47.647+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-09-06T14:59:47.648+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:47.648+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:59:47.649+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:47.680+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-04-30 00:00:00+00:00
[2022-09-06T14:59:47.700+0000] {standard_task_runner.py:52} INFO - Started process 449 to run task
[2022-09-06T14:59:47.704+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-04-30T00:00:00+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp1jd1ec2q', '--error-file', '/tmp/tmpchbiwxcs']
[2022-09-06T14:59:47.705+0000] {standard_task_runner.py:80} INFO - Job 446: Subtask postgres_to_s3
[2022-09-06T14:59:47.903+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-04-30T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:59:48.059+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-30T00:00:00+00:00
[2022-09-06T14:59:48.083+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:59:48.099+0000] {dag_with_postgres_hooks.py:29} INFO - save orders data in text file get_orders.txt
[2022-09-06T14:59:48.099+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T14:59:48.134+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220430T000000, start_date=20220906T145947, end_date=20220906T145948
[2022-09-06T14:59:48.213+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T14:59:48.281+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
