[2022-09-06T14:56:49.699+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-09-06T14:56:49.726+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-09-06T14:56:49.726+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:49.726+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:56:49.727+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:49.754+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-01 00:00:00+00:00
[2022-09-06T14:56:49.762+0000] {standard_task_runner.py:52} INFO - Started process 282 to run task
[2022-09-06T14:56:49.768+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-01T00:00:00+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpv0q8k962', '--error-file', '/tmp/tmpgzyx21or']
[2022-09-06T14:56:49.769+0000] {standard_task_runner.py:80} INFO - Job 430: Subtask postgres_to_s3
[2022-09-06T14:56:50.015+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:56:50.361+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-01T00:00:00+00:00
[2022-09-06T14:56:50.407+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:56:51.016+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    with open("dags/get_orders.txt" "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dags/get_orders.txtw'
[2022-09-06T14:56:51.046+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220501T000000, start_date=20220906T145649, end_date=20220906T145651
[2022-09-06T14:56:51.280+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 430 for task postgres_to_s3 ([Errno 2] No such file or directory: 'dags/get_orders.txtw'; 282)
[2022-09-06T14:56:51.368+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T14:56:51.565+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T14:59:47.913+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-09-06T14:59:47.938+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-09-06T14:59:47.938+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:47.939+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:59:47.939+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:47.971+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-01 00:00:00+00:00
[2022-09-06T14:59:47.976+0000] {standard_task_runner.py:52} INFO - Started process 451 to run task
[2022-09-06T14:59:47.980+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-01T00:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp41uvvo7v', '--error-file', '/tmp/tmp0p6opmbl']
[2022-09-06T14:59:47.981+0000] {standard_task_runner.py:80} INFO - Job 447: Subtask postgres_to_s3
[2022-09-06T14:59:48.116+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-01T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:59:48.273+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-01T00:00:00+00:00
[2022-09-06T14:59:48.304+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:59:48.317+0000] {dag_with_postgres_hooks.py:29} INFO - save orders data in text file get_orders.txt
[2022-09-06T14:59:48.317+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T14:59:48.361+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220501T000000, start_date=20220906T145947, end_date=20220906T145948
[2022-09-06T14:59:48.400+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T14:59:48.486+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
