[2022-09-06T14:56:56.033+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-09-06T14:56:56.057+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-09-06T14:56:56.057+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:56.058+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:56:56.058+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:56.094+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-14 00:00:00+00:00
[2022-09-06T14:56:56.104+0000] {standard_task_runner.py:52} INFO - Started process 312 to run task
[2022-09-06T14:56:56.109+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-14T00:00:00+00:00', '--job-id', '441', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp265sidih', '--error-file', '/tmp/tmppq_kp3_k']
[2022-09-06T14:56:56.110+0000] {standard_task_runner.py:80} INFO - Job 441: Subtask postgres_to_s3
[2022-09-06T14:56:56.308+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:56:56.525+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T00:00:00+00:00
[2022-09-06T14:56:56.546+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:56:56.557+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    with open("dags/get_orders.txt" "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dags/get_orders.txtw'
[2022-09-06T14:56:56.618+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220514T000000, start_date=20220906T145656, end_date=20220906T145656
[2022-09-06T14:56:56.664+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 441 for task postgres_to_s3 ([Errno 2] No such file or directory: 'dags/get_orders.txtw'; 312)
[2022-09-06T14:56:56.706+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T14:56:57.065+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T14:59:56.954+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-09-06T14:59:56.984+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [queued]>
[2022-09-06T14:59:56.984+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:56.984+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:59:56.985+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:57.023+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-14 00:00:00+00:00
[2022-09-06T14:59:57.031+0000] {standard_task_runner.py:52} INFO - Started process 478 to run task
[2022-09-06T14:59:57.040+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-14T00:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp8b829pg2', '--error-file', '/tmp/tmpbo6ckiuq']
[2022-09-06T14:59:57.041+0000] {standard_task_runner.py:80} INFO - Job 460: Subtask postgres_to_s3
[2022-09-06T14:59:57.179+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-14T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:59:57.330+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T00:00:00+00:00
[2022-09-06T14:59:57.354+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:59:57.367+0000] {dag_with_postgres_hooks.py:29} INFO - save orders data in text file get_orders.txt
[2022-09-06T14:59:57.367+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T14:59:57.396+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220514T000000, start_date=20220906T145956, end_date=20220906T145957
[2022-09-06T14:59:57.460+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T14:59:57.511+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
