[2022-09-05T17:56:43.861+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_04.greet scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T17:56:43.876+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_04.greet scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T17:56:43.876+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T17:56:43.876+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T17:56:43.876+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T17:56:43.914+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): greet> on 2022-09-04 00:00:00+00:00
[2022-09-05T17:56:43.918+0000] {standard_task_runner.py:52} INFO - Started process 3247 to run task
[2022-09-05T17:56:43.922+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_04', 'greet', 'scheduled__2022-09-04T00:00:00+00:00', '--job-id', '316', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp8xmosl8y', '--error-file', '/tmp/tmpel14xr6j']
[2022-09-05T17:56:43.922+0000] {standard_task_runner.py:80} INFO - Job 316: Subtask greet
[2022-09-05T17:56:44.016+0000] {task_command.py:371} INFO - Running <TaskInstance: our_dag_with_python_operator_04.greet scheduled__2022-09-04T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T17:56:44.133+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ancordss
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05T17:56:44.135+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 12, in greet
    name = ti.xcomx_pull(task_ids='get_name')
AttributeError: 'TaskInstance' object has no attribute 'xcomx_pull'
[2022-09-05T17:56:44.210+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_04, task_id=greet, execution_date=20220904T000000, start_date=20220905T175643, end_date=20220905T175644
[2022-09-05T17:56:44.291+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 316 for task greet ('TaskInstance' object has no attribute 'xcomx_pull'; 3247)
[2022-09-05T17:56:44.321+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-05T17:56:44.370+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
