[2022-09-05T18:14:53.353+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_06.greet scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T18:14:53.368+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_06.greet scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T18:14:53.368+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T18:14:53.369+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 6
[2022-09-05T18:14:53.369+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T18:14:53.389+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): greet> on 2022-09-04 00:00:00+00:00
[2022-09-05T18:14:53.394+0000] {standard_task_runner.py:52} INFO - Started process 4096 to run task
[2022-09-05T18:14:53.397+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_06', 'greet', 'scheduled__2022-09-04T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmplv2hu2yt', '--error-file', '/tmp/tmpggg6q2lo']
[2022-09-05T18:14:53.397+0000] {standard_task_runner.py:80} INFO - Job 337: Subtask greet
[2022-09-05T18:14:53.477+0000] {task_command.py:371} INFO - Running <TaskInstance: our_dag_with_python_operator_06.greet scheduled__2022-09-04T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T18:14:53.572+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ancordss
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_06
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05T18:14:53.573+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 1 required positional argument: 'age'
[2022-09-05T18:14:53.586+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_06, task_id=greet, execution_date=20220904T000000, start_date=20220905T181453, end_date=20220905T181453
[2022-09-05T18:14:53.600+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 337 for task greet (greet() missing 1 required positional argument: 'age'; 4096)
[2022-09-05T18:14:53.613+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-05T18:14:53.655+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
