[2022-09-06T14:56:55.689+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-09-06T14:56:55.781+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-09-06T14:56:55.781+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:55.781+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:56:55.782+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:55.868+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-12 00:00:00+00:00
[2022-09-06T14:56:55.880+0000] {standard_task_runner.py:52} INFO - Started process 311 to run task
[2022-09-06T14:56:55.896+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-12T00:00:00+00:00', '--job-id', '439', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpifbjidin', '--error-file', '/tmp/tmp2roji8hq']
[2022-09-06T14:56:55.897+0000] {standard_task_runner.py:80} INFO - Job 439: Subtask postgres_to_s3
[2022-09-06T14:56:56.154+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:56:56.394+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T00:00:00+00:00
[2022-09-06T14:56:56.421+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:56:56.433+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    with open("dags/get_orders.txt" "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dags/get_orders.txtw'
[2022-09-06T14:56:56.453+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220512T000000, start_date=20220906T145655, end_date=20220906T145656
[2022-09-06T14:56:56.576+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 439 for task postgres_to_s3 ([Errno 2] No such file or directory: 'dags/get_orders.txtw'; 311)
[2022-09-06T14:56:56.624+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T14:56:57.093+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T14:59:52.995+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-09-06T14:59:53.017+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-09-06T14:59:53.017+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:53.017+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:59:53.017+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:53.041+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-12 00:00:00+00:00
[2022-09-06T14:59:53.048+0000] {standard_task_runner.py:52} INFO - Started process 472 to run task
[2022-09-06T14:59:53.056+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-12T00:00:00+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp6p5wisvs', '--error-file', '/tmp/tmpbubb0fas']
[2022-09-06T14:59:53.056+0000] {standard_task_runner.py:80} INFO - Job 458: Subtask postgres_to_s3
[2022-09-06T14:59:53.162+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-12T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:59:53.286+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T00:00:00+00:00
[2022-09-06T14:59:53.309+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:59:53.324+0000] {dag_with_postgres_hooks.py:29} INFO - save orders data in text file get_orders.txt
[2022-09-06T14:59:53.324+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T14:59:53.346+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220512T000000, start_date=20220906T145952, end_date=20220906T145953
[2022-09-06T14:59:53.396+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T14:59:53.445+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
