[2022-09-06T14:56:54.396+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-09-06T14:56:54.415+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-09-06T14:56:54.415+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:54.415+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:56:54.416+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:56:54.471+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-11 00:00:00+00:00
[2022-09-06T14:56:54.503+0000] {standard_task_runner.py:52} INFO - Started process 308 to run task
[2022-09-06T14:56:54.546+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-11T00:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpv8ry4mcv', '--error-file', '/tmp/tmp1p1noq5c']
[2022-09-06T14:56:54.548+0000] {standard_task_runner.py:80} INFO - Job 438: Subtask postgres_to_s3
[2022-09-06T14:56:54.852+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:56:55.321+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-11T00:00:00+00:00
[2022-09-06T14:56:55.385+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:56:55.425+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    with open("dags/get_orders.txt" "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dags/get_orders.txtw'
[2022-09-06T14:56:55.462+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220511T000000, start_date=20220906T145654, end_date=20220906T145655
[2022-09-06T14:56:55.587+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 438 for task postgres_to_s3 ([Errno 2] No such file or directory: 'dags/get_orders.txtw'; 308)
[2022-09-06T14:56:55.664+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T14:56:55.801+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T14:59:52.703+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-09-06T14:59:52.724+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-09-06T14:59:52.725+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:52.725+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T14:59:52.725+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T14:59:52.763+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-11 00:00:00+00:00
[2022-09-06T14:59:52.776+0000] {standard_task_runner.py:52} INFO - Started process 471 to run task
[2022-09-06T14:59:52.785+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v01', 'postgres_to_s3', 'scheduled__2022-05-11T00:00:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpgdw90gy6', '--error-file', '/tmp/tmp4m2wh_4n']
[2022-09-06T14:59:52.787+0000] {standard_task_runner.py:80} INFO - Job 457: Subtask postgres_to_s3
[2022-09-06T14:59:52.951+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v01.postgres_to_s3 scheduled__2022-05-11T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T14:59:53.130+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-11T00:00:00+00:00
[2022-09-06T14:59:53.144+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T14:59:53.156+0000] {dag_with_postgres_hooks.py:29} INFO - save orders data in text file get_orders.txt
[2022-09-06T14:59:53.157+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T14:59:53.186+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v01, task_id=postgres_to_s3, execution_date=20220511T000000, start_date=20220906T145952, end_date=20220906T145953
[2022-09-06T14:59:53.242+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T14:59:53.296+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
